#!/bin/bash

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

if [ ! -d "$HOME/.tccli" ]
then
	echo "[+] Installing Dependencies....."
	mkdir "$HOME/.tccli"
	python3 -m venv "$HOME/.tccli/venv"
	touch "$HOME/.tccli/.keys"
	VIRTUAL_ENV="$HOME/.tccli/venv" "$HOME/.tccli/venv/bin/pip" install -r requirements.txt &>/dev/null
fi

cd $( dirname "${BASH_SOURCE[0]}" )

source "$HOME/.tccli/.keys"
VIRTUAL_ENV="$HOME/.tccli/venv" "$HOME/.tccli/venv/bin/python" main.py $@
