#!/bin/bash

export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

cd $( dirname "${BASH_SOURCE[0]}" )

if [ ! -d "$HOME/.tccli" ]
then
	echo "[+] Installing Dependencies....."
	mkdir "$HOME/.tccli"
	python3 -m venv "$HOME/.tccli/venv"
	cp  ".keys.sample" "$HOME/.tccli/.keys"
	VIRTUAL_ENV="$HOME/.tccli/venv" "$HOME/.tccli/venv/bin/pip" install -r requirements.txt &>/dev/null
fi

if [ "$1" = "config" ]
then
	nano "$HOME/.tccli/.keys"
else
	source "$HOME/.tccli/.keys"
	VIRTUAL_ENV="$HOME/.tccli/venv" "$HOME/.tccli/venv/bin/python" main.py $@
fi
